### ISSUE TITLE
Dependencies return error with stable version of Dart.

### ISSUE THREAD

**Issue by ghost** [wstrange/firebase_dart_ui#2]
Running 'pub get' returns 
`ERR: Package firebase_dart_ui requires SDK version >=2.0.0-dev.23.0 <2.0.0 but the current SDK is 2.0.0-dev.20.0.`

**Comment by wstrange** [comment]
Are you able to upgrade to >= 2.0.0-dev.23.0?

I think we want to target 2.0 stable once it is released

**Comment by wstrange** [comment]
I lowered the SDK constraint to 2.0.0-dev.20.0.
This should fix your issue.
