### ISSUE TITLE
"The operation has timed out" error only when debugging with IntelliJ

### ISSUE THREAD

**Issue by gazialankus** [wstrange/firebase_dart_ui#4]
I often get this with DDC (hitting play **[edit: debug, not play]** in IntelliJ). I never get this with dart2js (deploying it to Firebase hosting). But curiously, I don't get this on some days. **[edit: see my following comments, this only happens when the IntelliJ debugger is connected.]**

![image](https://user-images.githubusercontent.com/412997/43834174-e1ab31ec-9b15-11e8-9bd1-aa248e554181.png)

Here's the error I see on the console:
![image](https://user-images.githubusercontent.com/412997/43834268-2e91d1aa-9b16-11e8-8318-1d9d2e6b9f64.png)

This happens after coming back to my site from Google auth.

**Comment by wstrange** [comment]
I wonder if the underlying firebase js library needs to be updated.  I don't think I saw this before.

**Comment by gazialankus** [comment]
In my index.html I'm including firebase js 4.10.1 and firebaseui js 2.6.2, which is what's there in the example here: https://github.com/wstrange/firebase_dart_ui/blob/master/example/web/index.html

I remember trying different versions and having the same issue, but I'm happy to try it again if there are versions that you would suggest.

**Comment by wstrange** [comment]
I just updated the example app for Dart 2, and tested it with intellij. It works fine. Please give it a go and reopen if you still have problems.

**Comment by gazialankus** [comment]
Sorry I need to make a correction: I don't hit *play* in IntelliJ, I hit *debug*. 

I just upgraded my app like your example and I'm getting the same situation as before. Here's my detailed observation: When I start it with *debug* in IntelliJ, this error happens. However, pressing *stop* in IntelliJ and refreshing the browser (running without the debugger connected) does not create this error and works just fine.

I will now try the example in this repo.

**Comment by gazialankus** [comment]
Yes, the latest example here also has the same issue when debugged with IntelliJ. Here's how to reproduce: 

- Clone this repo
- Open the example folder in IntelliJ
- Enable Dart support and do pub get
- Right click web/index.html in IntelliJ and select debug
- Wait for webdev to finish compiling and hit debug once again
- Click google login and get the error: 

![screenshot - 8_11_2018 11_40_37 am](https://user-images.githubusercontent.com/412997/43989914-e22aa114-9d5b-11e8-9080-793682da91e0.png)

- Then see the timeout after that: 

![screenshot - 8_11_2018 11_40_52 am](https://user-images.githubusercontent.com/412997/43989919-eb3cd66e-9d5b-11e8-9bff-6e0c9eff835c.png)

(top-right of the screen below shows we're debugging)
![screenshot - 8_11_2018 11_41_08 am](https://user-images.githubusercontent.com/412997/43989926-1a8d93f4-9d5c-11e8-9b9f-ea57803dba00.png)


- Press stop in IntelliJ to stop debugging. Everything works fine now (note the top-right disabled stop button, which means we're not debugging): 

![screenshot - 8_11_2018 11_41_34 am](https://user-images.githubusercontent.com/412997/43989928-25a33dde-9d5c-11e8-9979-35ab9ca65d07.png)

**Edit:** I'm not sure if I have the permission to reopen this issue, could not find how to do that. Could you reopen it?

**Comment by wstrange** [comment]
I think this is more a general issue of debugging mixed dart /  JS code  using DDC.  I am not sure there is much I can do here as it is more of a general SDK / DDC issues

If you have any suggestions, I'm open to them..

**Comment by gazialankus** [comment]
Thanks. What's the best place to raise this issue?
